server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
  instance:
    hostname: gateway-service
    prefer-ip-address: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: calculate-service
          uri: lb://calculate-service
          predicates:
            - Path=/api/v1/calculate**
        - id: attendance-service
          uri: lb://attendance-service
          predicates:
            - Path=/api/v1/attendance/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employees/**
        - id: justify-service
          uri: lb://justify-service
          predicates:
            - Path=/api/v1/justify/**
        - id: extrahour-service
          uri: lb://extrahour-service
          predicates:
            - Path=/api/v1/extrahour/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    root: DEBUG
