server:
  port: 8080
  # port: 9500 # puede ser por el puerto
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # default-zone: http://localhost:8761/eureka
      # defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-service:8761/eureka # o defaultZone
  instance:
    # hostname: localhost # deberia eliminar?
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: calculate-service
          uri: lb://calculate-service
          predicates:
            - Path=/api/v1/calculate**
        - id: attendance-service
          uri: lb://attendance-service
          predicates:
            - Path=/api/v1/attendance/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employees/**
        - id: justify-service
          uri: lb://justify-service
          predicates:
            - Path=/api/v1/justify/**
        - id: extrahour-service
          uri: lb://extrahour-service
          predicates:
            - Path=/api/v1/extrahour/**
        - id: frontend-service
          uri: lb://frontend-service
          predicates:
            - Path=/**
            # - Path=/frontend/**
# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG
#     reactor.netty: DEBUG
#     root: DEBUG
